# Railway Environment Variables Configuration
# Copy and paste this into Railway's Secrets section

# Email Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
EMAIL_ADDRESS = "deepalirakshe24@gmail.com"
EMAIL_PASSWORD = "fjaygniasvajhqsb"

# Security
SECRET_KEY = "your-secret-key-here-change-in-production"
ADMIN_PASSWORD = "admin123"

# Event Configuration
EVENT_NAME = "Cognizant Pre-Placement Talk - Batch 2026"
EVENT_DATE = "18th September 2025"
EVENT_LOCATION = "Main Auditorium"

# Flask Configuration
FLASK_ENV = "production"
